permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Xin Miao
  email: machine.miao@gmail.com
  link: http://machinecc.github.io
  github: http://github.com/machinecc

# 站点信息
title: Xin 
description: 苗欣的博客
url: http://machinecc.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/machinecc/machinecc.github.io/master/images/avatar.jpg
favicon: https://raw.githubusercontent.com/machinecc/machinecc.github.io/master/images/favorite.ico

# google analytics 设置
ga:
  id: UA-64742203-1
  url: http://machinecc.github.io

# disqus 设置
disqus:
  shortname: machine_github


